<?php

namespace PauloAK\NfseLajeado\Helpers;

class Constants {

    const SIM = '1';
    const NAO = '2';

    const STATUS_NORMAL = '1';
    const STATUS_CANCELADO = '2';

    const REGIME_ESPECIAL_TRIBUTACAO_MICROEMPRESA_MUNICIPAL = '1';
    const REGIME_ESPECIAL_TRIBUTACAO_ESTIMATIVA = '2';
    const REGIME_ESPECIAL_TRIBUTACAO_SOCIEDADE_PROFISSIONAIS = '3';
    const REGIME_ESPECIAL_TRIBUTACAO_COOPERATIVA = '4';
    const REGIME_ESPECIAL_TRIBUTACAO_MEI = '5';
    const REGIME_ESPECIAL_TRIBUTACAO_ME_EPP = '6';

    const TIPO_RPS_DFS = '1';
    const TIPO_RPS_NOTA_FISCAL_CONJUGADA = '2';
    const TIPO_RPS_CUPOM = '3';

    const NATUREZA_OPERACAO_IMPOSTO_RECOLHIDO_PELO_REGIME_UNICO_TRIBUTACAO = '59';

}